version: "3.8"
services:
  postgresdb:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    volumes:
      - postgresGD:/var/lib/postgresql/data
      - ./local-run/init-postgresdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
volumes:
  api:
  postgresGD:
    driver: local
